# Generated by Django 4.0.3 on 2022-03-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('idvideos', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory_id', models.IntegerField(blank=True, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'videos',
                'managed': True,
            },
        ),
    ]
