# Generated by Django 4.0.3 on 2022-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('idimage', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('subcateoryid', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
    ]
