# Generated by Django 4.0.3 on 2022-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('idcategories', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=45)),
                ('website_id', models.IntegerField(blank=True, null=True)),
                ('link', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'categories',
                'managed': True,
            },
        ),
    ]
